spring:
  devtools:
    restart:
      additional-exclude: logs/**
  datasource:
    url: jdbc:mysql://localhost:3306/java_graphql?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  pattern:
    console:%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} 0 %msg%n
  level:
    org:
      hibernate:
        SQL: debug