# antigamente esse arquivo se chamava bootstrap.properties ou bootstrap.yml
server:
  port: 8080
spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: prod
#cuidado com essa parte pq é oculto por padrão por causa de segurança
management:
  endpoints:
    web:
      exposure:
        include: #'*'
          - refresh
greeting-service:
  greeting: "Olá"
  default-value: "Mundo"
